import { Scene } from '../types/scene';

export const SCENES_CONFIG: Scene[] = [
  {
    id: 'scene-1-exterior',
    index: 1,
    title: 'Arrival / Exterior',
    slug: 'arrival',
    durationVh: 100,
    doorType: 'none',
    cameraMove: {
      scale: [1.0, 1.28],
      xPercent: [0, 0],
      yPercent: [0, -6],
      ease: 'power2.inOut',
    },
    domContent: {
      sectionKey: 'hero',
      heading: 'ALEX MORGAN',
      subheading: 'Principal Software Architect & Full-Stack Systems Engineer',
      category: 'exterior',
    },
    layers: [
      {
        id: 's1-sky-mountains',
        name: 'Background Sky & Distant Horizon',
        src: '/assets/images/scene1/sky_bg',
        depth: 0.1,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -3] },
        scaleRange: [1.0, 1.03],
        opacityRange: [1.0, 0.0],
      },
      {
        id: 's1-building-facade',
        name: 'Modernist House Architecture',
        src: '/assets/images/scene1/building_facade',
        depth: 0.45,
        zIndex: 20,
        isCutout: true,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -8] },
        scaleRange: [1.0, 1.2],
        opacityRange: [1.0, 0.0],
      },
      {
        id: 's1-entrance-steps',
        name: 'Concrete Stairs & Courtyard Entrance',
        src: '/assets/images/scene1/entrance_steps',
        depth: 0.65,
        zIndex: 25,
        isCutout: true,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -14] },
        scaleRange: [1.0, 1.28],
        opacityRange: [1.0, 0.0],
      },
      {
        id: 's1-foreground-flora',
        name: 'Courtyard Desert Flora Framing',
        src: '/assets/images/scene1/foreground_flora',
        depth: 0.95,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [-4, 6], yRange: [0, -32] },
        scaleRange: [1.0, 1.42],
        opacityRange: [1.0, 0.0],
      },
    ],
  },
  {
    id: 'scene-2-threshold',
    index: 2,
    title: 'Entrance / Threshold',
    slug: 'threshold',
    durationVh: 100,
    doorType: 'sliding-double',
    cameraMove: {
      scale: [1.0, 1.35],
      xPercent: [0, 0],
      yPercent: [0, -4],
      ease: 'power2.inOut',
    },
    domContent: {
      sectionKey: 'threshold',
      heading: 'ENTER THE WORKSPACE',
      subheading: 'Exploring systems architecture from core to edge',
      category: 'threshold',
    },
    layers: [
      {
        id: 's2-corridor-deep',
        name: 'Deep Corridor Perspective & Ceiling Light Cove',
        src: '/assets/images/scene2/corridor_bg',
        depth: 0.15,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -4] },
        scaleRange: [1.0, 1.08],
        opacityRange: [0.0, 1.0],
      },
      {
        id: 's2-sliding-door-left',
        name: 'Architectural Door Panel Left',
        src: '/assets/images/scene2/door_panel_left',
        depth: 0.7,
        zIndex: 22,
        isCutout: true,
        dimensions: { width: 800, height: 1440 },
        parallax: { xRange: [0, -85], yRange: [0, 0] },
        scaleRange: [1.0, 1.15],
        opacityRange: [1.0, 1.0],
      },
      {
        id: 's2-sliding-door-right',
        name: 'Architectural Door Panel Right',
        src: '/assets/images/scene2/door_panel_right',
        depth: 0.7,
        zIndex: 22,
        isCutout: true,
        dimensions: { width: 800, height: 1440 },
        parallax: { xRange: [0, 85], yRange: [0, 0] },
        scaleRange: [1.0, 1.15],
        opacityRange: [1.0, 1.0],
      },
      {
        id: 's2-portal-frame',
        name: 'Threshold Portal Wall & Shadow Bevel',
        src: '/assets/images/scene2/portal_frame',
        depth: 0.9,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -26] },
        scaleRange: [1.0, 1.45],
        opacityRange: [1.0, 0.0],
      },
    ],
  },
  {
    id: 'scene-3-fullstack',
    index: 3,
    title: 'Full-Stack Development',
    slug: 'full-stack',
    durationVh: 120,
    doorType: 'hinge-left',
    cameraMove: {
      scale: [1.0, 1.3],
      xPercent: [0, 8],
      yPercent: [0, -3],
      ease: 'power2.inOut',
    },
    domContent: {
      sectionKey: 'skills',
      heading: 'FULL-STACK DEVELOPMENT',
      subheading: 'Modern web architectures, responsive systems, and end-to-end tooling',
      category: 'skills',
    },
    layers: [
      {
        id: 's3-room-interior-bg',
        name: 'Skylit Room Chamber with Wall Wash Lighting',
        src: '/assets/images/scene3/room_bg',
        depth: 0.2,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, -4], yRange: [0, -6] },
        scaleRange: [1.0, 1.1],
        opacityRange: [0.0, 1.0],
      },
      {
        id: 's3-door-hinge-left',
        name: 'Left Hinged Architectural Room Door',
        src: '/assets/images/scene3/door_hinge_left',
        depth: 0.72,
        zIndex: 25,
        isCutout: true,
        dimensions: { width: 720, height: 1440 },
        parallax: { xRange: [0, -15], yRange: [0, 0] },
        scaleRange: [1.0, 1.12],
        opacityRange: [1.0, 1.0],
        transformOrigin: 'left center',
      },
      {
        id: 's3-foreground-corridor-pillar',
        name: 'Foreground Corridor Wall Cutout',
        src: '/assets/images/scene3/corridor_pillar',
        depth: 0.95,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 600, height: 1440 },
        parallax: { xRange: [0, -35], yRange: [0, -28] },
        scaleRange: [1.0, 1.4],
        opacityRange: [1.0, 0.0],
      },
    ],
  },
  {
    id: 'scene-4-backend-ai',
    index: 4,
    title: 'Backend & AI Pipelines',
    slug: 'backend-ai',
    durationVh: 130,
    doorType: 'hinge-right',
    cameraMove: {
      scale: [1.0, 1.25],
      xPercent: [0, -6],
      yPercent: [0, -4],
      ease: 'power2.inOut',
    },
    domContent: {
      sectionKey: 'architecture',
      heading: 'BACKEND ARCHITECTURE & AI PIPELINES',
      subheading: 'Distributed microservices, vector search pipelines, and low-latency inference',
      category: 'architecture',
    },
    layers: [
      {
        id: 's4-indigo-chamber-bg',
        name: 'Indigo High-Contrast Tech Chamber Atmosphere',
        src: '/assets/images/scene4/indigo_chamber_bg',
        depth: 0.2,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 4], yRange: [0, -5] },
        scaleRange: [1.0, 1.08],
        opacityRange: [0.0, 1.0],
      },
      {
        id: 's4-door-hinge-right',
        name: 'Right Hinged Monolithic Chamber Door',
        src: '/assets/images/scene4/door_hinge_right',
        depth: 0.75,
        zIndex: 25,
        isCutout: true,
        dimensions: { width: 780, height: 1440 },
        parallax: { xRange: [0, 18], yRange: [0, 0] },
        scaleRange: [1.0, 1.14],
        opacityRange: [1.0, 1.0],
        transformOrigin: 'right center',
      },
      {
        id: 's4-foreground-edge',
        name: 'Corridor Perspective Foreground Framing',
        src: '/assets/images/scene4/corridor_edge',
        depth: 0.95,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 500, height: 1440 },
        parallax: { xRange: [0, 30], yRange: [0, -25] },
        scaleRange: [1.0, 1.38],
        opacityRange: [1.0, 0.0],
      },
    ],
  },
  {
    id: 'scene-5-gallery',
    index: 5,
    title: 'Web Application Gallery',
    slug: 'gallery',
    durationVh: 140,
    doorType: 'sliding-double',
    cameraMove: {
      scale: [1.0, 1.32],
      xPercent: [0, 0],
      yPercent: [0, -5],
      ease: 'power2.inOut',
    },
    domContent: {
      sectionKey: 'gallery',
      heading: 'FEATURED CASE STUDIES',
      subheading: 'Interactive SaaS platforms, design systems, and enterprise cloud applications',
      category: 'gallery',
    },
    layers: [
      {
        id: 's5-gallery-space-bg',
        name: 'Expansive Modern Gallery Space with Diffuse Light Ceiling',
        src: '/assets/images/scene5/gallery_space_bg',
        depth: 0.18,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -5] },
        scaleRange: [1.0, 1.1],
        opacityRange: [0.0, 1.0],
      },
      {
        id: 's5-pedestals-floor',
        name: 'Architectural Pedestals & Polished Floor Reflection',
        src: '/assets/images/scene5/pedestals_floor',
        depth: 0.5,
        zIndex: 20,
        isCutout: true,
        dimensions: { width: 2560, height: 800 },
        parallax: { xRange: [0, 0], yRange: [0, -12] },
        scaleRange: [1.0, 1.2],
        opacityRange: [1.0, 1.0],
      },
      {
        id: 's5-gallery-doors-left',
        name: 'Gallery Double Portal Left Door',
        src: '/assets/images/scene5/portal_door_left',
        depth: 0.7,
        zIndex: 22,
        isCutout: true,
        dimensions: { width: 650, height: 1440 },
        parallax: { xRange: [0, -70], yRange: [0, 0] },
        scaleRange: [1.0, 1.12],
        opacityRange: [1.0, 1.0],
      },
      {
        id: 's5-gallery-doors-right',
        name: 'Gallery Double Portal Right Door',
        src: '/assets/images/scene5/portal_door_right',
        depth: 0.7,
        zIndex: 22,
        isCutout: true,
        dimensions: { width: 650, height: 1440 },
        parallax: { xRange: [0, 70], yRange: [0, 0] },
        scaleRange: [1.0, 1.12],
        opacityRange: [1.0, 1.0],
      },
      {
        id: 's5-foreground-portal-arch',
        name: 'Foreground Portal Archway Framing',
        src: '/assets/images/scene5/portal_arch',
        depth: 0.95,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -30] },
        scaleRange: [1.0, 1.42],
        opacityRange: [1.0, 0.0],
      },
    ],
  },
  {
    id: 'scene-6-contact',
    index: 6,
    title: 'Contact / Destination',
    slug: 'contact',
    durationVh: 100,
    doorType: 'none',
    cameraMove: {
      scale: [1.0, 1.15],
      xPercent: [0, 0],
      yPercent: [0, -2],
      ease: 'power2.out',
    },
    domContent: {
      sectionKey: 'contact',
      heading: "LET'S BUILD SOMETHING GREAT",
      subheading: 'Available for high-impact architecture, engineering leadership, and bespoke web platforms.',
      category: 'contact',
    },
    layers: [
      {
        id: 's6-contact-wall-bg',
        name: 'Monolithic Architectural Feature Wall with Overhead Spotlight Cones',
        src: '/assets/images/scene6/contact_wall_bg',
        depth: 0.25,
        zIndex: 10,
        isCutout: false,
        dimensions: { width: 2560, height: 1440 },
        parallax: { xRange: [0, 0], yRange: [0, -4] },
        scaleRange: [1.0, 1.05],
        opacityRange: [0.0, 1.0],
      },
      {
        id: 's6-foreground-floor-plane',
        name: 'Polished Concrete Foreground Floor Reflection',
        src: '/assets/images/scene6/floor_reflection',
        depth: 0.9,
        zIndex: 40,
        isCutout: true,
        dimensions: { width: 2560, height: 600 },
        parallax: { xRange: [0, 0], yRange: [0, -18] },
        scaleRange: [1.0, 1.25],
        opacityRange: [1.0, 1.0],
      },
    ],
  },
];
